Get AG list based on Aadhaar number
tekdi/eg-backend pull request #199
Opened 2023-07-17 09:41 UTC by parthgandhitekdi

2023-07-24 08:00 UTC, yogesh-pawar-2023 commented on src/src/beneficiaries/beneficiaries.controller.ts
> +		});
need to return failure condition

2023-07-24 08:57 UTC, parthgandhitekdi commented on src/src/beneficiaries/beneficiaries.controller.ts
> +		});
Done

2023-07-25 07:35 UTC, manojLondhe requested changes

2023-07-25 07:35 UTC, manojLondhe commented on src/src/beneficiaries/beneficiaries.service.ts
> +				query MyQuery {
fix indent, use one tab with 4 width, for one level of indent

2023-07-25 07:35 UTC, manojLondhe commented on src/src/beneficiaries/beneficiaries.service.ts
> +		const resultData = (
add blank line after query

2023-07-25 07:35 UTC, manojLondhe commented on src/src/beneficiaries/beneficiaries.controller.ts
> +	@Post('byAadhaar')
rename route as

@Post('/admin/list/duplicates-by-aadhhar')

2023-07-25 07:35 UTC, manojLondhe commented on src/src/beneficiaries/beneficiaries.controller.ts
> +	async duplicateByAadhaar(
rename as
getBeneficiariesDuplicatesByAadhhar

2023-07-25 07:35 UTC, manojLondhe commented on src/src/beneficiaries/beneficiaries.service.ts
> +	async byAadhaar(aadhaarNo: string) {
rename as
getBeneficiariesDuplicatesByAadhhar

2023-07-25 11:42 UTC, merged