Task #204040 learner distribution status for prerak view api
tekdi/eg-backend pull request #304
Opened 2023-08-28 11:47 UTC by GitVivekHub

# I have ensured that following `Pull Request Checklist` is taken care of before sending this PR

* [x] Code is formatted as per format decided
* [x] Updated acceptance criteria in tracker
* [x] Updated test cases in test-cases-tracker
* [x] Updated new API endpoint if any in common postman collection
* [x] Updated DB changes in db-tracker if any

2023-08-29 11:00 UTC, parthgandhitekdi requested changes

2023-08-29 11:00 UTC, parthgandhitekdi commented on src/src/facilitator/facilitator.service.ts
> +					data: {},
data will be array.
Also send count and pages number.

2023-08-29 12:02 UTC, GitVivekHub commented on src/src/facilitator/facilitator.controller.ts
> +
resolved

2023-08-29 12:02 UTC, GitVivekHub commented on src/src/facilitator/facilitator.controller.ts
> +	async getLearnerStatusDistribution(
resolved

2023-08-29 12:02 UTC, GitVivekHub commented on src/src/facilitator/facilitator.service.ts
> +				 ]} `);
resolved

2023-08-29 12:03 UTC, GitVivekHub commented on src/src/facilitator/facilitator.service.ts
> +			offset: $offset,where: ${filterQuery},order_by: ${sortType}) {
resolved

2023-08-29 12:03 UTC, GitVivekHub commented on src/src/facilitator/facilitator.service.ts
> +			offset: $offset,where: ${filterQuery},order_by: ${sortType}) {
resolved

2023-08-29 12:03 UTC, GitVivekHub commented on src/src/facilitator/facilitator.service.ts
> +        }
resolved

2023-08-29 12:36 UTC, GitVivekHub commented on src/src/facilitator/facilitator.service.ts
> +			const count = res[0].learnerData.length;
here i am taking count of total learners for the prerak, as i am already getting all the learners for the prerak through relation hence i am taking count of those learners present in the learnerData

2023-08-29 12:44 UTC, GitVivekHub commented on src/src/facilitator/facilitator.service.ts
> +			let responseWithPagination = res.slice(offset, offset + limit);
resolved

2023-08-29 12:44 UTC, GitVivekHub commented on src/src/facilitator/facilitator.service.ts
> +		const count = res.length;
resolved

2023-08-29 12:44 UTC, GitVivekHub commented on src/src/facilitator/facilitator.service.ts
> +				)}}}}`,
resolved

2023-08-29 13:40 UTC, parthgandhitekdi approved these changes

2023-08-29 13:47 UTC, parthgandhitekdi requested changes
Need changes

2023-08-31 12:10 UTC, parthgandhitekdi requested changes

2023-08-31 12:22 UTC, parthgandhitekdi approved these changes

2023-08-31 12:23 UTC, merged