[BE]Task #206616 Camp attendance feature
tekdi/eg-backend pull request #401
Opened 2023-10-18 11:38 UTC by GitVivekHub

# I have ensured that following `Pull Request Checklist` is taken care of before sending this PR

* [x] Code is formatted as per format decided
* [x] Updated acceptance criteria in tracker
* [x] Updated test cases in test-cases-tracker
* [x] Updated new API endpoint if any in common postman collection
* [x] Updated DB changes in db-tracker if any

2023-10-18 13:49 UTC, sagarkoshti1990 requested changes

2023-10-18 13:49 UTC, sagarkoshti1990 commented on src/src/camp/camp.service.ts
> +
save direct document id as 
`photo_1: document_photo1, photo_2: document_photo2,`

2023-10-18 13:49 UTC, sagarkoshti1990 commented on src/src/camp/camp.service.ts
> +		);
save direct document id as 
`photo_1: document_photo1, photo_2: document_photo2,`

2023-10-19 05:07 UTC, GitVivekHub commented on src/src/camp/camp.service.ts
> +
resolved

2023-10-19 05:07 UTC, GitVivekHub commented on src/src/camp/camp.service.ts
> +		);
resolved

2023-10-19 05:55 UTC, sagarkoshti1990 approved these changes

2023-10-19 05:55 UTC, merged